name: Build and publish MAAS cloud-init rpm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:39
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo yum install -y git createrepo rpm-build rpm-sign wget gcc python3 yum-utils\
            python3-wheel python3-rpm python3-libs python3-idna python3-packaging python3-rpm python3-iniconfig \
            python3-pluggy python3-pytest python3-pysocks python3-pyyaml python3-six python3-urllib3 python3-urllib3 \
            python3-requests python3-responses python3-pytest-mock python3-devel python3-setuptools python3-pip python3-wheel \
            python3-pyrsistent python3-markupsafe python3-jsonpointer python3-attrs python3-jsonschema python3-jsonpatch \
            python3-jinja2 python3-pyserial python3-oauthlib python3-netifaces python3-configobj python3-passlib

      - name: Clone cloud-init and cloud-init rpm builder
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          git clone https://github.com/canonical/cloud-init.git /tmp/cloud-init-23.2.1/
          cp * /tmp/cloud-init-23.2.1/
          tar czf cloud-init-23.2.1.tar.gz -C /tmp cloud-init-23.2.1/
          mv cloud-init-23.2.1.tar.gz  ~/rpmbuild/SOURCES/cloud-init-23.2.1.tar.gz
          cp cloud-init.spec ~/rpmbuild/SPECS/
          cp cloud-init-tmpfiles.conf Do-not-enable-dhcp6-on-EC2.patch sources ~/rpmbuild/SOURCES/

      - name: rpmbuild check
        continue-on-error: true
        run: |
          rpmbuild -br --noclean --target noarch --nodeps ~/rpmbuild/SPECS/cloud-init.spec

      - name: rpmbuild artifact
        run: |
          rpmbuild -ba --noprep --noclean --target noarch --nodeps ~/rpmbuild/SPECS/cloud-init.spec